### ISSUE TITLE
Pattern generation internals

### ISSUE THREAD

**Issue by ginty** [Origen-SDK/o2#18]
In O1, a vector object was created in memory every time `tester.cycle` was called.
This object took a snapshot of things like the current timeset and the pin values and stored additional things like comments and microcode.
At the end of the pattern these vectors were rendered out to a file based on how the current tester liked to format them.

However, this vector object proved to be an unsatisfactory intermediate representation for two main reasons:

* It wasn't abstract enough. It was coupled to the current tester - the pin values were already formatted how the current tester liked them which meant that it was only suitable as an intermediate representation leading to the current tester, but not for any other endpoints.
* It was a static snapshot. The pin values were captured as an ASCII string which meant that it could not be used to replay the pattern for simulation or conversion to another format.

For 02 I propose the following architecture:

During generation a pattern is built up in memory as a list of actions. All of the user APIs to generate pattern content (tester.cycle, pin.drive, tester.set_timeset, etc.) will all have a very simple outcome which is to add an action to the list, which should be very fast.
There will likely be a few different types of actions (PinAction, TimesetAction, TesterAction, etc.), and Rust [seems to be able to handle arrays of different types](https://stackoverflow.com/questions/27957103/how-do-i-create-a-heterogeneous-collection-of-objects) as required for this.

This intermediate format will be very efficient by only capturing changes instead of all pin values for all vectors. So it should be very fast to create and low on memory usage.

The various tester targets would then simply replay this list and render their specific format.

Rust naturally supports multi-threading (another one of the benefits you get from writing code that satisfies the compiler is that it is guaranteed to be thread-safe) and this arch will work well in a multi-core scenario where we could have one core running the Python code to generate the actions, and then additional Rust-only threads running on other cores to render the actions as they come in.

It should also be easier to create efficient pattern readers with this model. Pattern readers would be implemented in pure Rust and would bypass the user API altogether (pin.drive, etc.) and simply look for the changes between vectors and convert them directly to action objects.

Please everyone feel free to comment on this below with further ideas and/or related requests.

**Comment by pderouen** [comment]
So, would this be a 1 dimension array containing 1 action each? Or, would there be some organization of actions into a vector object?

**Comment by pderouen** [comment]
I guess based on https://github.com/Origen-SDK/o2/issues/19 it would have to be 1d to allow the flexibility.

**Comment by ginty** [comment]
It would just be a big 1D list.
It's not really a collection of vectors, or really any concept of a vector object. It is just the sequence of events that the pattern needs to play.
Each item in the list would be one action, and there could be multiple actions associated with each cycle/vector (which itself is an action).

Something like this (note that the nesting is in the formatting for readability only, the data structure is flat):

~~~
[
  <SetTimesetAction timeset="func">,
  <PinAction pin="tdi" data="1" operation="drive">,
  <PinAction pin="tdo" data=None operation="dont_care">,
  <PinAction pin="tdo" data=None operation="dont_care">,
  <CycleAction repeat=None>,
  <PinAction pin="tdo" data=None operation="dont_care">,
  <RegAction name="myreg" address=0x10000000 data=0x12345678 operation="write">,
    <JTAGAction data=0x10 size=8 operation="write" target="ir">,
      <PinAction pin="tms" data=1 operation="drive">,
      <CycleAction repeat=None>,
      <PinAction pin="tms" data=0 operation="drive">,
      <PinAction pin="tdi" data=1 operation="drive">,
      <CycleAction repeat=None>,
       ...
    <JTAGAction/>,
    <JTAGAction data=0x1000000012345678 size=64 operation="write" target="dr">,
      <PinAction pin="tms" data=1 operation="drive">,
      <CycleAction repeat=None>,
      <PinAction pin="tms" data=0 operation="drive">,
      <PinAction pin="tdi" data=1 operation="drive">,
      <CycleAction repeat=None>,
       ...
    <JTAGAction/>
  <RegAction/>
  ...
]
~~~

**Comment by ginty** [comment]
No reason why it couldn't be nested like that mind you, and probably some minor performance benefit to doing it like that when rendering a protocol-level output (easier to skip the pin actions).
Don't think we should mandate either way right now though, that can come out in the wash during implementation, i.e. if it's not too hard to do the nesting.

**Comment by pderouen** [comment]
This is probably beyond the scope of this discussion. but... Maybe there should be 1 or more parallel data structures to help easily locate where in this giant 1D array a particular type of action occurs. If I want to modify a previously generated vector like o1 allows, it would be good to have another smaller array that points to each cycle action (and it's associated count). That makes it quick and easy to know where a new action should be inserted.

Actually, now that I'm thinking about it (and not wanting to re-type this comment again), it really makes sense to do one or the other (bundle the actions in cycle action groups, or separately track the location of cycle actions).

**Comment by ginty** [comment]
The user wouldn't have access to this thing, so it will be much more hidden that maybe it appeared to (power?) users in O1.
The ability to retrospectively modify recent vectors was useful though.

Not sure about collecting into cycle groups though or having special tracking of cycles - the idea is that this action list is just as valid for a list of reg-level operations only as it is for a run that contains the concept of vector cycles.

I would say that we present a similar user API to O1 to allow the user to express an event that should happen 2 cycles ago.
Then "add_an_action_to_the_list" function would either push it onto the end by default, or if a -2 cycles argument was present, it would just look back from the end of the list until it found 2 cycle actions and insert it there.

**Comment by ginty** [comment]
O2 patgen will use a full AST representation which will support cycle-level and PA outputs being generated from the same AST.
See this PR for details - https://github.com/Origen-SDK/o2/pull/92
