### ISSUE TITLE
Crash on Windows when outside of workspace

### ISSUE THREAD

**Issue by pderouen** [Origen-SDK/o2#20]
https://github.com/Origen-SDK/o2/blob/64e584707e8736df7107db8d0ffcfcfc639e8190/rust/origen/src/core/utility/logger.rs#L128-L131

The HOME environment variable does not exist by default in Windows.

**Comment by coreyeng** [comment]
See `step 0` of the README, which addresses this. O2 isn't setting `HOME` if it doesn't exist, and I'm really not sure if it even should.

**Comment by pderouen** [comment]
Could we not instead define a home equivalent if running under Windows? Most tools you use don't require environment variables to be setup. Windows can already point you to the current user's document folder (for example).

If possible, this time around, it would be great if functionality on Windows was seamless and "native" instead of Linux-ified. :)

**Comment by ginty** [comment]
Also consider that if it can't work out a HOME then it should maybe log to the console only and emit a warning that it is not logging to a file because it can't work out what the user home dir is

**Comment by pderouen** [comment]
Good point
