### ISSUE TITLE
Pin Lookups, Groups, and Aliasing

### ISSUE THREAD

**Issue by coreyeng** [Origen-SDK/o2#25]
Hello,

As I'm working on #21, I'm following pretty closely to what O1 does, but am wondering if there's any changes we'd like to make at this stage. For instance:

1. Do we want to separate `pins` vs. `pin_groups`? `Pins[name]`, implies to me that its a single object, and hence when I do `add_pin('gpioa', size: 5)` I get 5 individual pins added, not just a single pin group. Would it be better to separate this into two functions. For instance:

~~~python
add_pin('gpioa', size=5) #=> Creates 5 pins, and 1 pin group
pin('gpioa') #=> None
pin('gpioa0') #=> Pin for gpioa0
pin_group('gpioa') #=> Pin Group for gpioa
pin_group('gpioa0') #=> None
~~~

This would also have the benefit of returning a consistent class (or `None`, if it doesn't exists).

2. From #22, we'd want `pins` and, if applicable, `pin_groups` to return as Dictionary, or Dictionary-like object. In O1, if you do `dut.pins` in O1 you'd see only pin names, without aliases. Do we want to keep this the same, or include aliases here as well? I'm thinking about how something like `in` would be overridden to return `true` on a pin alias. We can, of course, do that but it'd be extra Python code. I wonder if we should just return pins + aliases at the outset. Another, Rust-implemented, function of `unique_pins`, or something along those lines could be added to get all non-aliased pin names.

Anyway, just something to think about.

**Comment by ginty** [comment]
(1) sounds good to me.

For (2) I think it should be a dictionary-like - i.e. behave mostly like a dict, but also be smart enough to seamless handle aliases.

I think it should behave like this:

~~~python
add_pin("pin1")
add_pin("pin2")
add_pin_alias("p2", "pin2")

# It does only contain 2 real pins
pins.len()    # => 2

# But works with 3 names!
pins["pin1"]   # => <pin>
pins["pin2"]   # => <pin>
pins["p1"]     # => None
pins["p2"]     # => <pin> 
~~~

I would expect `in` and so on to say `True` for `"p2"` also.

Anything else would make application code have to think about whether they were using the main ID vs. an alias, whereas the point of an alias is allow application code to use the name they prefer and pretend like it is a 1st class pin.

For the console display of this collection object, feel free to make that much better than O1 - e.g. maybe showing a listing of all pins with their aliases in brackets.
That's what I'm planning to do for the equivalent reg collection objects.

**Comment by coreyeng** [comment]
What would you have just iterators, or just a 'grab all available' method do? I was thinking of returning (at first) just a pretty-print of a dictionary like Python does, but I think it'd be confusing if you see more stuff when you print it out than its length. Likewise, iterators could be a bit confusing as well. Should they iterate over everything? Or just unique pins? I could see a case for the former during doc generation.

**Comment by coreyeng** [comment]
To build a bit on `1)` too: I was planning to still require unique pin and groups names. That is, you couldn't have both a pin and pin group named `reset`, but you'd have to access it with the right method. Do you agree?

**Comment by ginty** [comment]
Iterators should just iterate over the physical objects, so 2 items in the above example.
If it had a name component to it (equivalent to Ruby's `pins.each do |name, pin|`) then in that case the name should be the primary ID.

**Comment by ginty** [comment]
Don't feel strongly one way or the other re. allowing matching pin and pin_group names, though if they are separate collections why would we block it?

**Comment by coreyeng** [comment]
Okay. So you would keep all operations other than 'get' or 'in' then as only operating on physical pins? That makes sense to me.

For matching names for pin/groups, that just came from O1 behavior. Since they were stored the same object, we couldn't do that there. I think that `pins` and `pin_groups` is different enough to where someone shouldn't confuse `pins['reset']` with `pin_groups['reset']`.

**Comment by pderouen** [comment]
I'm not sold on the forced separation of pins and groups of pins. They're really not so different. I think the separation is going to add needless complexity. Just thinking of something like the pattern_pin_order statement. Now, I have to interrogate 2 different objects for each item in the list to figure out which API to use? Aren't all of the underlying methods going to be practically identical anyway? There should probably be a pin_or_group as well.

**Comment by coreyeng** [comment]
They're different enough to where Rust has to treat them separately, which is why I brought this up, or else we risk just wasting memory space. Its probably not a big deal but early enough to start thinking about it.

Anyway, the two are different in some keys ways but, like you said, are alike as well. Its more a matter of if we want to explicitly show that you're accessing a pin vs. pin group. Going to Python's mantra of 'Explicit is better than implicit', the two are different enough to where they could be separated out. For example, I wasn't planning to put a `size` method on a Pin, so something like `pin_sizes = [len(p) for p in dut.pins]` would crash, and we'd either have to implement the same methods for both (keeping in mind that the implementation is happening in Rust), or you'd have to check that the member function exists during the loop. Not sure how often that'd be used, but just an example.

As for `pin_pattern_order`, I think since @ginty wants pins at the model level, allowing for them to be nested in the DB, we'll probably need to give it either full paths or the instance itself from Python, which Rust will translate. I think we'll be seeing API changes there, and in anything else with more intricate pin accesses, regardless.

A `pin_or_group` method wouldn't work if we're allowing both to share names as well.

**Comment by info-rchitect** [comment]
Can a pin have multiple aliases within the same scope/mode?

**Comment by coreyeng** [comment]
Do you mean can you assign a pin to multiple aliases? Yes, that will still be allowed.

**Comment by coreyeng** [comment]
I think everything here has hit in the pin API. There's a scope are mentioned, but that wasn't the crux of this issue and I think is mentioned in another ticket.
