### ISSUE TITLE
Add CLI File handler

### ISSUE THREAD

**Issue by ginty** [Origen-SDK/o2#3]
All validating of file arguments and decomposing of .list arguments should be done by the Rust CLI.

It should expose an API to python for it to retreive the files, something like:

~~~python
file_handler.number_of_files_remaining   # => 2
file_handler.all_files    # => ["app/patterns/pat1.py", "app/patterns/pat2.py"]
file_handler.next   # =>  "app/patterns/pat1.py"
file_handler.number_of_files_remaining   # => 1
file_handler.next   # =>  "app/patterns/pat2.py"
file_handler.next   # =>  None
file_handler.number_of_files_remaining   # => 0
~~~

**Comment by coreyeng** [comment]
I think this has been added in #70 and can be closed?

**Comment by ginty** [comment]
Yeah, I think it can be closed, though still has some features missing e.g. list decomposition.
I'll add specific tickets for that, thanks!
