### ISSUE TITLE
Discussion of register bit manipulation

### ISSUE THREAD

**Issue by chrisnappi** [Origen-SDK/o2#32]
In O1 we added in the ability to manipulate bits fairly late in the game, and the syntax is a bit odd:

~~~ruby
dut.myblock.reg(:myreg).write! do |r|
  r.bits(:thing1).write(0x4) 
  r.bits(:thing2).write(1) 
end
~~~

I think in O2 we should build in bit manipulation from the ground up which should hopefully lead to more natural mechanism.

**Comment by ginty** [comment]
I didn't think the O1 API was so bad, main thing that was weird to me was that it had write called in both the outer loop and the inner.

Maybe this gets us out of the struggles we were having with `apply()` over on #23.

We could have it that `write` and `verify` were always active methods (that invoked the register read/write) and that the only way to do multiple sub-bits were within a transaction block:

~~~python
# You can set data in a register without triggering an action, like this. This gets
# out of the O1 weirdness of using write() to setup for a read
dut.my_reg.my_bitx.set_data(5)
dut.my_reg.my_bity.set_data(0x100)
# The to do the verify(with all reg bits being compared):
dut.my_reg.verify()

# On the other hand, you can combine the set_data and verify (or write), but this would
# trigger two transactions:
dut.my_reg.my_bitx.verify(5)
dut.my_reg.my_bity.verify(0x100)

# To get an equivalent single transaction you would use the transaction block:
with txn(dut.my_reg) as reg:
  reg.my_bitx.verify(5)
  reg.my_bity.verify(0x100)
~~~

Thoughts?

**Comment by ginty** [comment]
So, I couldn't do it exactly as I have it above, but this what we have working:

~~~python
from origen import write_transaction, verify_transaction

with write_transaction(dut.my_reg) as reg:
        reg.my_field1.set_data(1)
        reg.my_field2.set_data(2)

# Also works with a field as the target within the transaction body
with write_transaction(dut.my_reg.my_big_field) as f:
        f[10].set_data(1)
        f[32:15].set_data(0x5A)

# Same thing for a verify (read) operation, only bits update in the body will be read
with verify_transaction(dut.my_reg) as reg:
        reg.my_field1.set_data(1)
        reg.my_field2.set_data(2)
~~~

Not the prettiest, but that's Python for you I'm afraid and difficult to see how to make it much better.

Note that opinions are closed anyway @chrisnappi after not providing any thoughts on the original proposal :-)

**Comment by chrisnappi** [comment]
That looks good.  To me it is much more clear than the O1 syntax.  Sorry but I hate '!'.

**Comment by ginty** [comment]
Ah OK, wasn't sure exactly what you were objecting to in the O1 version.
I do agree actually, and I think O2 will be much clearer without the "!" and from separating the data setting from the operation request.

**Comment by chrisnappi** [comment]
Yeah, we had many cases of people putting additional '!'s inside the 'do' - which caused very subtle wrong behavior...  Thanks!

**Comment by ginty** [comment]
This is now available in master, API as above.
