### ISSUE TITLE
Translator for remote files

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/o2#35]
We need a good test case for IP-XACT so I can write a Rust based XML importer that will first address the register API.  Here is an [article regarding some option](http://www.erahm.org/2017/05/24/a-rust-based-xml-parser-for-firefox/)s.  It seems like Rust does not yet have a fully featured XML parser so I will start a [Python importer](https://www.geeksforgeeks.org/xml-parsing-python/) for IP-XACT.

**Comment by info-rchitect** [comment]
![my_first_python_commit](https://user-images.githubusercontent.com/26782653/71203852-6aacb980-2264-11ea-9b56-b1c254949251.PNG)

It has begun!

**Comment by ginty** [comment]
Here's a rust XML reader/writer here if you are interested - https://github.com/tafia/quick-xml

**Comment by ginty** [comment]
After thinking about this some more, I'm not sure that this is so useful in terms of a Rust benchmark, but it is very important infrastructure nonetheless.

I think what this should be doing is importing the XML and writing out a [block dir structure](https://github.com/Origen-SDK/o2/tree/master/example/example/blocks).
That will naturally lazy-load at runtime and so should remain quick to boot even for large designs.

So probably if this importer is done in Python then it doesn't have to go anywhere near Rust, and while a pure Rust implementation might be quicker, it probably is not that big a deal if an offline import process does not have every last drop of performance eked out of it.

**Comment by info-rchitect** [comment]
I think I will write a Rust and a Python version so we can compare and as a training exercise for me.

**Comment by info-rchitect** [comment]
Is there a recommended API nomenclature for importing external file formats we want to use at the Python level?  

~~~python
import_ip_xact(remote_file_path) # explicited
import_remote(remote_file_path) # let an interpreter discern the type of remote, similar to O1
~~~

**Comment by info-rchitect** [comment]
@ginty Should the translator be instantiated upon application boot?

~~~python
import origen
import _origen
import importlib
import os.path
import re
import pdb

from origen.controller import TopLevel
from origen.translator import Translator

class Base:
    # Returns the unique ID (name) of the app/plugin
    name =  _origen.app_config()["name"]
    translator = Translator()
~~~

Second question is should we use some sort of delegation to reserve a 'translate' method that the translator would always handle for the application?



~~~

**Comment by ginty** [comment]
> Is there a recommended API nomenclature for importing external file formats we want to use at the Python level?

I quite like the cuteness of automatically detecting the file type, but we definitely don't need that. So just implement a user driven IP-XACT selection for now, and then we can add an auto-detecting method on top later.

> @ginty Should the translator be instantiated upon application boot?

I don't think so. I don't think we should support a import operation invoked from application code - that is proven to not scale and just results in people building apps that can really suffer with boot up time.

So we should be aiming for an `origen import` command here, but for now hack together any way you like to boot the thing and we will eventually hook it up to a command.

**Comment by info-rchitect** [comment]
Discussion moved to [this PR](https://github.com/Origen-SDK/o2/pull/42)

**Comment by info-rchitect** [comment]
Will re-open new PRs for specific types of import/export as needed
