### ISSUE TITLE
Adding new Python code and unit tests documentation

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/o2#41]
Hi,

Could someone write up a quick doc on how to add new Python code and unit tests?  I know I can figure it out but if we have a working methodology then publishing it will make things more consistent and help new contributors.

thx

**Comment by info-rchitect** [comment]
I can do this as soon as the register model is merged as I need a test case.  The same need is required for Rust additions.

**Comment by ginty** [comment]
I've assigned this back to you, please add a wiki page to document your experience.

I think the key points from what is there already is:

- Adding new code to the origen module/namespace is simply a case of adding a new file to https://github.com/Origen-SDK/o2/tree/master/python/origen
- An application will already have that origen directory in its load path and from there normal Python rules for how to import and use such code would apply e.g. `from origen.my_sub_module import MyClass`
- Example tests exist here https://github.com/Origen-SDK/o2/tree/master/example/tests
- To run them execute `poetry run pytest` from the o2/example directory

**Comment by info-rchitect** [comment]
@ginty will do

**Comment by info-rchitect** [comment]
[done](https://github.com/Origen-SDK/o2/wiki/Python-First-Commit)
