### ISSUE TITLE
Python source files/directories usage model

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/o2#46]
Hi,

We had a consistent pattern in o1 where we made a file named `mycode.rb` and also made a directory `mycode` that contained supporting Ruby files.  Do we plan to follow this usage model in o2?

thx

**Comment by info-rchitect** [comment]
[This commit](https://github.com/Origen-SDK/o2/pull/42/commits/443a424ae929a917d4bb81eca49d870973041c7c) shows to implement relative imports similar to o1

**Comment by info-rchitect** [comment]
Added a [wiki](https://github.com/Origen-SDK/o2/wiki/Python-Relative-Import)

**Comment by ginty** [comment]
Note that `__init__.py` is not required for this to work as our minimum version of Python or above.

You only need that if you wish to do some initialization operations the first time the given module is imported.

**Comment by info-rchitect** [comment]
fixed
