### ISSUE TITLE
Register mask/enable methods

### ISSUE THREAD

**Issue by ginty** [Origen-SDK/o2#81]
What should the polarity be for masking? I think I got this wrong for O1 and want to make sure that I get it right for O2...

Say we have a method called `my_reg.read_mask()` where the intention is to return a value where a 1 or 0 indicates whether a specific bit is enabled for read or not.

What should a 1 mean when returned from such a method?

Should we have methods named `mask()` and `enable_mask()` to return the opposite state? Is `enable_mask()` a contradiction? Are there better names for this?

Honestly, I have hardly ever used masks so I would appreciate guidance from those who have and who feel that they have an intuitive sense for how these things should work.

**Comment by chrishume** [comment]
On the design side, a mask value of 1 usually means let the but through for
read/write.

**Comment by chrishume** [comment]
Bit, not but.  Phone autocorrected me.

**Comment by pderouen** [comment]
I think of it the opposite way (set mask = 1 to enable masking, disable reading, block the operation). But, I can make sense of the other way as well. 

Really what we're typically using the mask to do is enable or disable comparisons for the data contained in the bit. Would <code>compare_enable</code> or some other variation work?

**Comment by ginty** [comment]
Yeah, I think we should stay away from `mask` then as it can obviously mean different things to different people.
`enable` is fine, or also flags, `my_reg.read_flags()`, `my_reg.capture_flags()`, etc.

**Comment by chrishume** [comment]
Agreed. Enable removes the ambiguity.

**Comment by ginty** [comment]
Went with `my_reg.read_enables()`, `capture_enables()` and `overlay_enables()`.
